blog/urls.py
from django.urls import path 

from .import views

app_name = 'blog'

urlpatterns = [
    

    path('', views.BlogView.as_view(), name='blogview'),

    path('<slug>/', views.BlogDetail.as_view(), name='blogdetail'),

    path('search/', views.SearchView.as_view(), name='search'),


] 

costumebase/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    
    path('', include('products.urls', namespace='product')),

    path('cart/', include('cart.urls', namespace='cart')),
    
    path('order/', include('order.urls', namespace='order')),
    
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

    path('blog/', include('blog.urls', namespace='blog')),




    path('register/', include('accounts.urls', namespace='register')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),


]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path 

from .import views

app_name = 'order'

urlpatterns = [
    

    
    path('checkout/', views.Checkout.as_view(), name='checkout'),

    path('payment/', views.PaymentView.as_view(), name='payment'),

    path('razor/', views.razor, name='razor'),
    path('success/',views.payment_success, name="payment-success"),



    path('checkoutt/', views.checkoutt.as_view(), name='chekcoutt'),

    # path('orderproduct/', views.orderproduct, name='orderproduct'),

    path('user-order/', views.user_orders, name='user-order'),

    path('orderdetail/<int:id>', views.user_orderdetail, name='user-orderdetail'),

    path('order_product_detail/<int:id>/<int:oid>', views.user_order_product_detail, name='user_order_product_detail'),







] 

order/models.py
from django.db import models

from django_countries.fields import CountryField

from cart.models import *



STATUS = (


        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),

    )


METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("RazorPay", "RazorPay"),
    ("Stripe", "Stripe"),
)

class Order(models.Model):

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    # vendor = models.ForeignKey(Vendor, related_name='vendors_order', on_delete=models.CASCADE, null=True, blank=True)

    code = models.CharField(max_length=5, editable=False )
    ref_code = models.CharField(max_length=50, blank=True)
    total = models.FloatField()
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.TextField(blank=True)

    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    ordered = models.BooleanField(default=False)

    first_name = models.CharField(max_length=10, blank=True)
    last_name = models.CharField(max_length=10, blank=True)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    address_optional = models.CharField(blank=True, max_length=150)
    country = models.CharField(blank=True, max_length=50)
    city = models.CharField(blank=True, max_length=20)
    province = models.CharField(blank=True, max_length=100)
    zip = models.CharField(blank=True, max_length=100)

    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)

    order_status = models.CharField(max_length=50, blank=True, choices=STATUS) # gotta change this one

    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','phone','address',
        'address_optional', 'country', 'city', 'province', 'zip', 'adminnote']

# class OrderForm(ModelForm):
#     class Meta:
#         model = Order
#         fields = ['first_name','last_name',
#         'address','phone','city','country']

class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Processing', 'Processing'),
        ('Shipped', 'Shipped'),
        ('Delivered', 'Delivered'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, related_name='vendor_orderproduct', on_delete=models.CASCADE, null=True, blank=True)

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL,blank=True, null=True) # relation with varinat
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    variant_amount = models.FloatField(blank=True, null=True)

    status = models.CharField(max_length=10, choices=STATUS, default='New')
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.product.name


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    city = models.CharField(max_length=100)
    province = models.CharField(max_length=100)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name_plural = '2. Addresses'


class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    orders = models.ForeignKey(Order, related_name='vendor_payment', on_delete=models.CASCADE, blank=True, null=True)
    amount = models.FloatField()
    order_id = models.CharField(max_length=100)
    payment_id = models.CharField(max_length=100)
    paid = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.order_id


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

    class Meta:
        verbose_name_plural = '3. Coupons'


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

    class Meta:
        verbose_name_plural = '4. Refund'


    

order/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from .models import Address




PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)

class CheckoutForm(forms.Form):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    phone = forms.CharField(required=True)
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    city = forms.CharField(required=False)
    province = forms.CharField(required=False)
    shipping_zip = forms.CharField(required=False)


    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))


class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)


class Account(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ('user',)
        fields = (
            'street_address', 'apartment_address', 'country','zip',
            'address_type', 'default',
        )

order/templates/check.html
{% extends "base.html" %}

{% load static %}
{% block content %}


<div id="all">
  <div id="content">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <!-- breadcrumb-->
          <nav aria-label="breadcrumb">
         
          </nav>
        </div>
        <div id="checkout" class="col-lg-9">
          <div class="box">



            <Form action="" method="post">
              {% csrf_token %}
              <div class="col-md-6">
                  <div class="billing-details">
          
                      <div class="section-title">
                          <h4 class="title">Shipping Details</h4>
                      </div>
                      <p><label for="id_first_name">First name:</label>




                          <input type="text" name="first_name" 
                           value="{{ user.userprofile.first_name }}" class="input"
                           maxlength="10" required id="id_first_name">
                        
                        
                        
                        </p>
                      <p><label for="id_last_name">Last name:</label>
                          <input type="text" name="last_name"  
                          value="{{ user.userprofile.last_name }}" class="input" maxlength="10" required id="id_last_name"></p>
                      <p><label for="id_address">Address:</label>

                          <input type="text" name="address" 
                          value="{{ user.userprofile.address }}" class="input" maxlength="150" id="id_address"></p>


                      <p><label for="id_address_optional">Address Optional:</label>

                          <input type="text" name="address_optional" 
                          value="{{ user.userprofile.address_optional }}" class="input" maxlength="150" id="id_address_optional"></p>


                      <p><label for="id_phone">Phone:</label>
                          <input type="text" name="phone" 
                           value="{{ user.userprofile.phone }}"  class="input" maxlength="20" id="id_phone"></p>



                      <p><label for="id_city">City:</label>

                          <select name="city" class="input" id="id_city">
                              <option value="{{ profile.city }}" selected>{{ user.userprofile.city }}</option>
                              <option value="İstanbul">Istanbul</option>
                              <option value="Ankara">Ankara</option>
                              <option value="İzmir">Izmir</option>
                              <option value="Bursa">Bursa</option>
                              <option value="Konya">Konya</option>
                              <option value="Yozgat">Yozgat</option>
                          </select></p>

                      <p><label for="id_first_name">Country :</label>
                          <input type="text" name="country" class="input" id="id_country" value="{{ user.userprofile.country }}"></p>
                      <p><label for="id_province">province :</label>

                          <input type="text" name="province" class="input" id="id_country" value="{{ user.userprofile.province }}"></p>
                      <p><label for="id_zip">zip :</label>
                          <input type="text" name="zip" class="input" id="id_zip" value="{{ user.userprofile.zip }}"></p>

                          <label for="">Note Order</label>

                          <textarea type="text" name="adminnote" id="id_adminnote" value="{{order.adminnote}}"></textarea>

                      <div class="pull-right">
                          <button  type="submit" class="primary-btn">Complete Order</button>
                      </div>
                  </div>
              </div>
          
      
          
          </Form>


                </div>
                <!-- /.box-->
              </div>



    
              <!-- /.col-md-3-->
    
        

              </div>
        </div>
      </div>
    </div>
   

{% endblock content %}

order/templates/checkout.html
{% extends "base.html" %}

{% load static %}

{% block content %}


        <!--====== App Content ======-->
        <div class="app-content">

            <!--====== Section 1 ======-->
            <div class="u-s-p-y-60">

                <!--====== Section Content ======-->
                <div class="section__content">
                    <div class="container">
                        <div class="breadcrumb">
                            <div class="breadcrumb__wrap">
                                <ul class="breadcrumb__list">
                                    <li class="has-separator">

                                        <a href="index.html">Home</a></li>
                                    <li class="is-marked">

                                        <a href="checkout.html">Checkout</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--====== End - Section 1 ======-->


            <!--====== Section 2 ======-->
            <div class="u-s-p-b-60">

                <!--====== Section Content ======-->
                <div class="section__content">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <div id="checkout-msg-group">
                                
                                    <!-- <div class="msg">

                                        <span class="msg__text">Have a coupon?

                                            <a class="gl-link" href="#have-coupon" data-toggle="collapse">Click Here to enter your code</a></span>
                                        <div class="collapse" id="have-coupon" data-parent="#checkout-msg-group">
                                            <div class="c-f u-s-m-b-16">

                                                <span class="gl-text u-s-m-b-16">Enter your coupon code if you have one.</span>
                                                <form class="c-f__form">
                                                    <div class="u-s-m-b-16">
                                                        <div class="u-s-m-b-15">

                                                            <label for="coupon"></label>

                                                            <input class="input-text input-text--primary-style" type="text" id="coupon" placeholder="Coupon Code"></div>
                                                        <div class="u-s-m-b-15">

                                                            <button class="btn btn--e-transparent-brand-b-2" type="submit">APPLY</button></div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--====== End - Section Content ======-->
            </div>
            <!--====== End - Section 2 ======-->


            <!--====== Section 3 ======-->
            <div class="u-s-p-b-60">

                <!--====== Section Content ======-->
                <div class="section__content">
                    <div class="container">
                        <div class="checkout-f">
                            <div class="row row--center">
                                <div class="col-lg-6">
                                    <h1 class="checkout-f__h1">DELIVERY INFORMATION</h1>

                                    <form action="" method="POST" class="checkout-f__delivery">
                                        {% csrf_token %}
                                        <div class="u-s-m-b-30">
                                            <div class="u-s-m-b-15">

                                                <!--====== Check Box ======-->
                                                <!-- <div class="check-box">

                                                    <input type="checkbox" id="get-address">
                                                    <div class="check-box__state check-box__state--primary">

                                                        <label class="check-box__label" for="get-address">Use default shipping and billing address from account</label></div>
                                                </div> -->
                                                <!--====== End - Check Box ======-->
                                            </div>

                                            <!--====== First Name, Last Name ======-->
                                            <div class="gl-inline">
                                                <div class="u-s-m-b-15">

                                                    <label class="gl-label" for="billing-fname">FIRST NAME *</label>

                                                    <input class="input-text input-text--primary-style" type="text" name="first_name" 
                                                    value="{{ user.userprofile.first_name }}" required id="id_first_name" data-bill=""></div>
                                                <div class="u-s-m-b-15">

                                                    <label class="gl-label" for="billing-lname">LAST NAME *</label>

                                                    <input class="input-text input-text--primary-style" type="text" name="last_name"  
                                                    value="{{ user.userprofile.last_name }}" required id="id_last_name" data-bill=""></div>
                                            </div>
                                            <!--====== End - First Name, Last Name ======-->

                                            <!--====== PHONE ======-->
                                            <div class="u-s-m-b-15">

                                                <label class="gl-label" for="billing-phone">PHONE *</label>

                                                <input class="input-text input-text--primary-style" type="text" name="phone" 
                                                value="{{ user.userprofile.phone }}" required id="id_phone" data-bill=""></div>
                                            <!--====== End - PHONE ======-->


                                            <!--====== Street Address ======-->
                                            <div class="u-s-m-b-15">

                                                <label class="gl-label" for="billing-street">STREET ADDRESS *</label>

                                                <input class="input-text input-text--primary-style" type="text" name="address" 
                                                value="{{ user.userprofile.address }}" required id="id_address" placeholder="House name and street name" data-bill=""></div>

                                            <div class="u-s-m-b-15">

                                                <label for="billing-street-optional"></label>

                                                <input class="input-text input-text--primary-style" type="text" name="address_optional" 
                          value="{{ user.userprofile.address_optional }}" id="id_address_optional" placeholder="Apartment, suite unit etc. (optional)" data-bill=""></div>
                                            <!--====== End - Street Address ======-->


                                            <!--====== Country ======-->
                                            <div class="u-s-m-b-15">

                                                <!--====== Select Box ======-->

                                                <label class="gl-label" for="billing-country">COUNTRY *</label>
                                                <select class="select-box select-box--primary-style" name="country" id="id_country" data-bill="">
                                                    <option value="{{ user.userprofile.country }}" selected>{{ user.userprofile.country }}</option>
                                                    <option value="uae">(UAE)</option>
                                                    <option value="uk"> (UK)</option>
                                                    <option value="us">(US)</option>
                                                </select>
                                                <!--====== End - Select Box ======-->
                                            </div>
                                            <!--====== End - Country ======-->


                                            <!--====== Town / City ======-->
                                            <div class="u-s-m-b-15">

                                                <label class="gl-label" for="billing-town-city">TOWN/CITY *</label>
                                                    <select class="select-box select-box--primary-style" name="city" id="id_city" data-bill="">
                                                        <option value="{{ profile.city }}" selected>{{ user.userprofile.city }}</option>
                                                        <option value="uae">A City</option>
                                                        <option value="uk">B City</option>
                                                        <option value="us">C City</option>
                                                    </select>
                                            
                                            </div>
                                            <!--====== End - Town / City ======-->


                                            <!--====== STATE/PROVINCE ======-->
                                            <div class="u-s-m-b-15">

                                                <!--====== Select Box ======-->

                                                <label class="gl-label" for="billing-state">STATE/PROVINCE *</label>
                                                
                                                <input class="input-text input-text--primary-style" type="text" name="province"
                                                id="id_province" value="{{ user.userprofile.province }}" id="id_province" placeholder="State/Province" data-bill="">
                                                <!--====== End - Select Box ======-->
                                            </div>
                                            <!--====== End - STATE/PROVINCE ======-->


                                            <!--====== ZIP/POSTAL ======-->
                                            <div class="u-s-m-b-15">

                                                <label class="gl-label" for="billing-zip">ZIP/POSTAL CODE *</label>

                                                <input class="input-text input-text--primary-style" type="text" name="zip"
                                                id="id_zip" value="{{ user.userprofile.zip }}" required id="billing-zip" placeholder="Zip/Postal Code" data-bill="">
                                                </div>
                                            <!--====== End - ZIP/POSTAL ======-->
                                            <div class="u-s-m-b-10">

                                                <!--====== Check Box ======-->
                                                
                                                <!--====== End - Check Box ======-->
                                            </div>
                                            
                                          
                                            <div class="u-s-m-b-10">

                                                <label class="gl-label" for="order-note">ORDER NOTE</label>
                                                
                                                <textarea class="text-area text-area--primary-style"
                                                 name="adminnote" id="id_adminnote"></textarea></div>
                                            <div>

                                       
                                                <div>

                                                    <button class="btn btn--e-transparent-brand-b-2" type="submit">Ship Here</button></div>
                                         
                                            
                                            
                                            </div>
                                        </div>
                                    </form>


                                </div>



                            </div>
                        </div>
                    </div>
                </div>
                <!--====== End - Section Content ======-->
            </div>
            <!--====== End - Section 3 ======-->
        </div>
        <!--====== End - App Content ======-->


        <!--====== Main Footer ======-->
      

        <!--====== Modal Section ======-->


        <!--====== Shipping Address Add Modal ======-->
      
        <!--====== End - Shipping Address Add Modal ======-->


        <!--====== Shipping Address Add Modal ======-->
     
        <!--====== End - Shipping Address Add Modal ======-->
        <!--====== End - Modal Section ======-->
   
    <!--====== End - Main App ======-->


    <!--====== Google Analytics: change UA-XXXXX-Y to be your site's ID ======-->
      
{% endblock content %}

order/templates/order_Form.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<Form action="" method="post">
    {% csrf_token %}
    <div class="col-md-6">
        <div class="billing-details">

            <div class="section-title">
                <h4 class="title">Shipping Details</h4>
            </div>
            <p><label for="id_first_name">First name:</label>
                <input type="text" name="first_name"  value="{{ user.first_name }}" class="input" maxlength="10" required id="id_first_name"></p>
            <p><label for="id_last_name">Last name:</label>
                <input type="text" name="last_name"  value="{{ user.last_name }}" class="input" maxlength="10" required id="id_last_name"></p>
            <p><label for="id_address">Address:</label>
                <input type="text" name="address" value="{{ profile.address }}" class="input" maxlength="150" id="id_address"></p>
            <p><label for="id_phone">Phone:</label>
                <input type="text" name="phone"  value="{{ profile.phone }}"  class="input" maxlength="20" id="id_phone"></p>
            <p><label for="id_city">City:</label>
                <select name="city" class="input" id="id_city">
                    <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                    <option value="İstanbul">Istanbul</option>
                    <option value="Ankara">Ankara</option>
                    <option value="İzmir">Izmir</option>
                    <option value="Bursa">Bursa</option>
                    <option value="Konya">Konya</option>
                    <option value="Yozgat">Yozgat</option>
                </select></p>
            <p><label for="id_first_name">Country :</label>
                <input type="text" name="country" class="input" id="id_country" value="{{ profile.country }}"></p>
            <div class="pull-right">
                <button  type="submit" class="primary-btn">Complete Order</button>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="shiping-methods">
            <div class="section-title">
                <h4 class="title">Payment Information</h4>
            </div>
            <p><label for="id_first_name">Total: {{ total }} USD </label>
                <input type="text" name="total" class="input" readonly value="${{ total }}"></p>
            <p><label for="id_first_name">Credit Card Holder</label>
                <input type="text" name="holder" class="input"  value=""></p>
            <p><label for="id_first_name">Credit Card Number</label>
                <input type="text" name="number" class="input"  value=""></p>
            <p><label for="id_first_name">Credit Exp Date/Year</label>
                <input type="text" name="ecpdate" class="input"  placeholder="mm/yy"></p>
            <p><label for="id_first_name">Security Number</label>
                <input type="text" name="secnumber" class="input"  value=""></p>
        </div>
    </div>
    

</Form>
{% endblock content %}

order/templates/razor.html
<html>
<head>
    <title></title>
</head>
<body>


    <div>
        <h2>
            Welcome to Razor pay
        </h2>
    </div>

<head>
    <style>
        .center {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>

<div class="center">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <p class="mb-3">
    Help us create more videos by donating 500 INR
    </p>


<!-- <form action="{% url 'order:razor' %}" method="POST"> -->

<h1><a href="{% url 'order:razor' %}"></a> Eat me</h1>

</form>

</div>
</div> 

</body>
</html>