blog/urls.py
from django.urls import path 

from .import views

app_name = 'blog'

urlpatterns = [
    

    path('', views.BlogView.as_view(), name='blogview'),

    path('<slug>/', views.BlogDetail.as_view(), name='blogdetail'),

    path('search/', views.SearchView.as_view(), name='search'),


] 

costumebase/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    
    path('', include('products.urls', namespace='product')),

    path('cart/', include('cart.urls', namespace='cart')),
    
    path('order/', include('order.urls', namespace='order')),
    
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

    path('blog/', include('blog.urls', namespace='blog')),




    path('register/', include('accounts.urls', namespace='register')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),


]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path 

from .import views

app_name = 'dashboard'

urlpatterns = [
    
 # ----------------------------------------- Vendor -------------------------------------

    path('index/', views.dashboard, name='index'),

    path('chart/', views.Chart.as_view(), name='chart'),

    path('add-product/', views.Add_Product.as_view(), name='add-product'),

    path('product-list/', views.Product_List.as_view(), name='product-list'),

    path('add-image/', views.add_image, name='add-image'),
    path('add-variant/', views.add_product_variation, name='add-varaint'),
    path('image-list/', views.Image_list.as_view(), name='image-list'),

    path('new-order/', views.New_Order_list.as_view(), name='new-order'),



    path('delivered-product-list/', views.Delivered_Product_list.as_view(), name='delivered-product-list'),
    path('detail-delivered-product/<int:pk>/', views.Detail_Delivered_Product.as_view(), name='detail-delivered-product'),

    #.......................................... Chart ........................................

    path('pie/', views.pie_chart, name = 'pie'),
    path('population-chart/', views.population_chart, name='population-chart'),
    path('chart/sales/<int:year>/', views.get_sales_chart, name='chart-sales'),

    




    # -------------------------------------- Customer -----------------------------------

    path('user-profile/', views.Customer_Profile.as_view(), name='user-profile'),
    path('user-dashboard/',views.User_Dashboard.as_view(), name='user-dashboard'),
    path('user-order/', views.User_Order.as_view(), name='user-order'),


    # ........................................ Message .................................

    path("chat/<str:username>", views.vendor_chat, name="vendor_chat"),


    path('user-message/', views.User_Message.as_view(), name='user-message'),

    path('message-detail/<int:pk>/', views.Message_Detail.as_view(), name='message_detail'),


    
]

order/urls.py
from django.urls import path 

from .import views

app_name = 'order'

urlpatterns = [
    

    
    path('checkout/', views.Checkout.as_view(), name='checkout'),

    path('payment/', views.PaymentView.as_view(), name='payment'),

    path('razor/', views.razor, name='razor'),
    path('success/',views.payment_success, name="payment-success"),



    path('checkoutt/', views.checkoutt.as_view(), name='chekcoutt'),

    # path('orderproduct/', views.orderproduct, name='orderproduct'),

    path('user-order/', views.user_orders, name='user-order'),

    path('orderdetail/<int:id>', views.user_orderdetail, name='user-orderdetail'),

    path('order_product_detail/<int:id>/<int:oid>', views.user_order_product_detail, name='user_order_product_detail'),







] 

products/urls.py
from django.urls import path 

from .import views

app_name = 'product'

urlpatterns = [


   
    path('', views.LandingPage.as_view(), name='index'),

    path('products/', views.Product_Index.as_view(), name='product-index'),
    # path('product-detail/<slug>/',views.Product_Detail.as_view(), name='product-detail'),
    path('add_to_wish/<int:id>/', views.add_to_wish, name ='add_to_wish'),

    path('product-detail/<int:id>/<slug:slug>/', views.product_detail, name='product-detail'),

    


    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),

    path('addcomment/<int:id>/', views.addcomment, name='addcomment'),


    path('category/<slug>/', views.Category_Detail.as_view(), name='category-detail'),


   
    # Search
    path('search/', views.SearchView.as_view(), name='search'),
    path('auto/', views.auto, name='auto'),


    # Wishlist

    path('wish/', views.Wish_View.as_view(), name='wish'),
    path('delete_wish_item/<int:id>/', views.delete_wish_item, name='delete_wish_item'),



    # Shop
    path('shops/', views.Shops.as_view(), name='shops'),
    path('free-shipping/', views.Free_Shipping.as_view(), name='free-shipping'),

    # Filter
    path('filterMdata/',views.filter_data, name='filter_data'),
    path('product-list/', views.Product_List.as_view(), name='product-list'),


    # Message

    path('send-message/<int:id>/<str:name>/',views.send_massage, name='send-message'),

    # path('product-detail-message/<int:id>/', views.massage, name='product-detail-message'),

    # path('detail/', views.)

    path("messages/", views.index, name="index"),

    path("message_search/", views.search, name="message_search"),

    path("addfriend/<str:name>", views.addFriend, name="addFriend"),
    
    path("chat/<str:username>", views.chat, name="chat"),
    
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),
   

]

search/models.py
from django.db import models

# Create your models here.

products/forms.py
from django import forms
from dashboard.models import Messages


class MessageForm(forms.ModelForm):
    class Meta:
        model = Messages
        exclude = ['sender_name',]
        fields = ['description']

products/views.py
from django import forms
from django.db.models.aggregates import Max, Min
from django.shortcuts import redirect, render, get_object_or_404
from django.views import generic
from django.views.generic import TemplateView
from django.views.generic.list import MultipleObjectMixin
from django.core.exceptions import ObjectDoesNotExist
from django.template.loader import render_to_string
from django.contrib import *
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, Q, query
from itertools import chain, product
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
import json
from .models import *
from order.models import OrderProduct
from cart.models import *
from .forms import MessageForm

# def shopcartcount(userid):
#     count = ShopCart.objects.filter(user_id=userid).count()
#     print('')
#     return count

class SearchView(generic.ListView):
    model = Product
    template_name = 'search_list.html'    
    paginate_by = 2
    # context_object_name = 'object_list'

    def get_queryset(self, *args, **kwargs):
            # qs = super().get_queryset(*args, **kwargs)
            product = Product.objects.all()
            # shop = Shop.objects.all()
            query = self.request.GET.get('q')

            if query:

                product = Product.objects.filter(Q(name__icontains=query)|Q(description__icontains=query)).distinct()
                # queryset = Shop.objects.filter(Q(name__icontains=query)|Q(discription__icontains=query)).distinct()

                # queryset = list(
                #     sorted(
                #         chain(product),
                #         key=lambda objects: objects.pk
                #     ))
            return product
            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context
    


def auto(request):
    query = request.GET.get('term')
    product = Product.objects.filter(Q(name__icontains=query)|Q(description__icontains=query)).distinct()
    # queryset = Shop.objects.filter(Q(name__icontains=query)|Q(discription__icontains=query)).distinct()
    # autoo = chain(queryset, product)
    mylist = []
    mylist += [x.name for x in product]
    return JsonResponse(mylist, safe=False)


class LandingPage(generic.TemplateView):
    template_name = 'message_user.html'





class Product_Index(generic.ListView):
    model = Product
    template_name = 'index.html'
    context_object_name = 'queryset'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user
        context['recent'] = Product.objects.filter(is_for_sale=True).order_by('-created_at')[0:15]

        context['cart'] = ShopCart.objects.filter(user_id=current_user.id)

        context['variant'] = Variants.objects.all() 
        context['topcat'] = Category.objects.filter(top_category=True)[:7]
        print( context['topcat'] )
        return context



# class Product_Detail(generic.DetailView):
#     model = Product
#     template_name = 'product-detail-variable.html'
#     context_object_name = 'queryset'

#     def get_queryset(self):
#         return super().get_queryset() 

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['category'] = Category.objects.all()
#         return context


def product_detail(request,id,slug):
    query = request.GET.get('q')
    
    category = Category.objects.all()

    product = Product.objects.get(pk=id)

    vendor_message = product.vendor.user.username
    message_user = list(User.objects.all())

    for user in message_user:
        if user.username == request.user.username:
            message_user.remove(user)
            break
    try:
        message_user = message_user[:10]
    except:
        message_user = message_user[:]

    bar = 0
    sold_product = OrderProduct.objects.filter(product_id=id)
    for i in sold_product:
        bar += i.quantity
   
    related_product = Product.objects.filter(category=product.category).exclude(id=id)[:15]
    images = Images.objects.filter(product_id=id)
    comments = Comment.objects.filter(product_id=id, status='True')
    
    wish_count =  Wishlist.objects.filter(product_id=id).count()



    context = {'product': product, 'related_product': related_product, 'bar':bar,
               'category': category,'images': images, 'comments': comments,
                'message_user':message_user, 'vendor':vendor_message,'wish_count':wish_count,
               }

    if product.variant !="None": # Product have variants
        if request.method == 'POST': #if we select color
            variant_id = request.POST.get('variantid')
            variant = Variants.objects.get(id=variant_id) #selected product by click color radio
            colors = Variants.objects.filter(product_id=id,size_id=variant.size_id )
            sizes = Variants.objects.raw('SELECT * FROM  products_variants  WHERE product_id=%s GROUP BY size_id',[id])
            query += variant.name+' Size:' +str(variant.size) +' Color:' +str(variant.color)
        else:
            variants = Variants.objects.filter(product_id=id)
            colors = Variants.objects.filter(product_id=id,size_id=variants[0].size_id )
            sizes = Variants.objects.raw('SELECT * FROM  products_variants  WHERE product_id=%s GROUP BY size_id',[id])
            variant =Variants.objects.get(id=variants[0].id)



        context.update({'sizes': sizes, 'colors': colors,
                        'variant': variant,'query': query,})
                        
    return render(request,'product-detail-variable.html',context)




@login_required(login_url='/register/customer_login/')
def add_to_wish(request, id):
    item = get_object_or_404(Product, id=id)
    wish_item, created = Wishlist.objects.get_or_create(
        product=item,
        user=request.user
    )
    
    if created:
        messages.info(request, "item added to your wish")
    else:
        messages.warning(request, "item was alrady in your wish")
    return redirect('product:product-index')



@login_required(login_url='/register/customer_login/')
def delete_wish_item(request, id):
    item = get_object_or_404(Product, id=id)
    wish_item = Wishlist.objects.filter(product=item, user=request.user).delete()
    messages.info(request, "item just deleted from your wishlist")
    return redirect('product:wish')



from django.utils.decorators import method_decorator
from .decorators import customer_required


@method_decorator([login_required, customer_required], name='dispatch')
class Wish_View(generic.ListView):
    model = Wishlist
    template_name = 'wish.html'
    context_object_name = 'queryset'
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user
        context['wish_view'] = self.model.objects.filter(user_id=current_user.id)
        context['cart'] = ShopCart.objects.filter(user_id=current_user.id)
        context['variant'] = Variants.objects.all() 
        context['topcat'] = Category.objects.filter(top_category=True)[:7]
        print( context['topcat'] )
        return context




def ajaxcolor(request):
    data = {}
    if request.POST.get('action') == 'post':
        size_id = request.POST.get('size')
        productid = request.POST.get('productid')
        colors = Variants.objects.filter(product_id=productid, size_id=size_id)
        context = {
            'size_id': size_id,
            'productid': productid,
            'colors': colors,
        }
        data = {'rendered_table': render_to_string('color_list.html', context=context)}
        return JsonResponse(data)
    return JsonResponse(data)



# @login_required(login_url='/register/customer_login/')
@customer_required
def addcomment(request, id):
   url = request.META.get('HTTP_REFERER')  # get last url
   current_user= request.user.buyer
   print(current_user, "lasjdflajsfdlajsdfl")
   #return HttpResponse(url)
   product = Product.objects.get(id=id)
   print(product.id, "lolllllll")
   form = CommentForm(request.POST or None)
   if request.method == 'POST':  # check post
       
       if form.is_valid():
           data = Comment()  # create relation with model
           data.name = form.cleaned_data['name']
           data.subject = form.cleaned_data['subject']
           data.comment = form.cleaned_data['comment']
           data.rate = form.cleaned_data['rate']
           data.ip = request.META.get('REMOTE_ADDR')
           data.product_id=product.id
           print(current_user, "fuck yes")
           data.user=current_user
           data.save()  # save data to table
           messages.success(request, "Your review has ben sent. Thank you for your interest.")
           return redirect('product:product-detail', id=product.id, slug=product.slug)

   return render(request, "comment.html", {'form':form, 'product':product})

class Category_Detail(generic.DetailView, MultipleObjectMixin):
    model = Category
    template_name = 'category-grid-left.html'
    paginate_by = 2
    # context_object_name = 'data'

    def get_context_data(self, **kwargs):
        object_list = Product.objects.filter(category=self.object)
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['category'] = Category.objects.all()
        return context

class Shops(generic.ListView):
    model = Shop
    template_name = 'shop-list-full.html'
    context_object_name = 'queryset'
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shop_count'] = Shop.objects.all().count()
        context['category'] = Category.objects.all()

search/views.py
from django.shortcuts import render

# Create your views here.

products/templates/color_list.html
{% comment %}
  


<!-- <input type="hidden" name="size" id="size" value="{{ size_id }}">
<ul class="color-option" >
    <li><span class="text-uppercase">Color:</span></li>
    {% for rs in colors %}
        <input type="radio" name="variantid" id="variantid" value="{{ rs.id }}" onchange="this.form.submit();">
        <li >
            <a href="#" style="background-color:{{ rs.color.code }}; color: #D9D9D9; text-shadow: 1px 1px #000000; width: 70px" >
                {{ rs.color }} ${{ rs.price }}
            </a>
            <img src="{{ rs.image }}" style="height: 70px">
        </li>
    {% endfor %}
</ul> -->

{% endcomment %}

<input type="hidden" name="size" id="size" value="{{ size_id }}">
{% for rs in colors %}
<div class="color__radio">

    <input type="radio"  {% if variant.id == rs.id %} checked {% endif %} 
    name="variantid" id="variantid" value="{{ rs.id }}"
     onchange="this.form.submit();">

    <label class="color__radio-label" for="jet" {% if variant.id == rs.id %} class="active" {% endif %}>

        <a>
             <img src="{{ rs.image }}" style="height: 50px">
        </a>                                        
    </label>                                         
</div>    
{% endfor %}

products/templates/customer_dashboard_sidebar.html
{% load static %}




<div class="dash__box dash__box--bg-white dash__box--shadow u-s-m-b-30">
    <div class="dash__pad-1">

        <span class="dash__text u-s-m-b-16">Hello, John Doe</span>
        <ul class="dash__f-list">
            <li>

                <a href="{% url 'dashboard:user-dashboard' %}">Manage My Account</a>
            </li>
            <li>

                <a class="dash-active" href="{% url 'dashboard:user-profile' %}">My Profile</a>
            </li>
            <li>

                <!-- customer_dashboard_sidebar.html -->
                <a class="dash-active"
                    href="{% if request.user.is_authenticated %}{% url 'product:chat' request.user.username %}{% else %}#{% endif %}">Message</a>
                <!-- <li>

                <a href="dash-track-order.html">Track Order</a></li> -->
            <li>

                <a href="{% url 'order:user-order' %}">My Orders</a>
            </li>

            <li>

                <a href="dash-cancellation.html">My Returns & Cancellations</a>
            </li>
            <li>

                <a href="{% url 'logout' %}">Logout</a>
            </li>
        </ul>
    </div>
</div>
<div class="dash__box dash__box--bg-white dash__box--shadow dash__box--w">
    <div class="dash__pad-1">
        <ul class="dash__w-list">
            <li>
                <div class="dash__w-wrap">

                    <span class="dash__w-icon dash__w-icon-style-1"><i class="fas fa-cart-arrow-down"></i></span>

                    <span class="dash__w-text">{{order_count.count}}</span>

                    <span class="dash__w-name">Orders Placed</span>
                </div>
            </li>
            <li>
                <div class="dash__w-wrap">

                    <span class="dash__w-icon dash__w-icon-style-2"><i class="fas fa-times"></i></span>

                    <span class="dash__w-text">{{order_canceld}}</span>

                    <span class="dash__w-name">Cancel Orders</span>
                </div>
            </li>
            <li>
                <div class="dash__w-wrap">

                    <span class="dash__w-icon dash__w-icon-style-3"><i class="far fa-heart"></i></span>

                    <span class="dash__w-text">0</span>

                    <span class="dash__w-name">Wishlist</span>
                </div>
            </li>
        </ul>
    </div>
</div>

products/templates/dash-cancellation.html
{% extends "base.html" %}

{% load static %}


{% block content %}
  


        <!--====== App Content ======-->
        <div class="app-content">

            <!--====== Section 1 ======-->
            <div class="u-s-p-y-60">

                <!--====== Section Content ======-->
                <div class="section__content">
                    <div class="container">
                        <div class="breadcrumb">
                            <div class="breadcrumb__wrap">
                                <ul class="breadcrumb__list">
                                    <li class="has-separator">

                                        <a href="index.html">Home</a></li>
                                    <li class="is-marked">

                                        <a href="dash-cancellation.html">My Account</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--====== End - Section 1 ======-->


            <!--====== Section 2 ======-->
            <div class="u-s-p-b-60">

                <!--====== Section Content ======-->
                <div class="section__content">
                    <div class="dash">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-3 col-md-12">

                                    <!--====== Dashboard Features ======-->
                                    <div class="dash__box dash__box--bg-white dash__box--shadow u-s-m-b-30">
                                        <div class="dash__pad-1">

                                            <span class="dash__text u-s-m-b-16">Hello, John Doe</span>
                                            <ul class="dash__f-list">
                                                <li>

                                                    <a href="dashboard.html">Manage My Account</a></li>
                                                <li>

                                                    <a href="dash-my-profile.html">My Profile</a></li>
                                                <li>

                                                    <a href="dash-address-book.html">Address Book</a></li>
                                                <li>

                                                    <a href="dash-track-order.html">Track Order</a></li>
                                                <li>

                                                    <a href="dash-my-order.html">My Orders</a></li>
                                                <li>

                                                    <a href="dash-payment-option.html">My Payment Options</a></li>
                                                <li>

                                                    <a class="dash-active" href="dash-cancellation.html">My Returns & Cancellations</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="dash__box dash__box--bg-white dash__box--shadow dash__box--w">
                                        <div class="dash__pad-1">
                                            <ul class="dash__w-list">
                                                <li>
                                                    <div class="dash__w-wrap">

                                                        <span class="dash__w-icon dash__w-icon-style-1"><i class="fas fa-cart-arrow-down"></i></span>

                                                        <span class="dash__w-text">4</span>

                                                        <span class="dash__w-name">Orders Placed</span></div>
                                                </li>
                                                <li>
                                                    <div class="dash__w-wrap">

                                                        <span class="dash__w-icon dash__w-icon-style-2"><i class="fas fa-times"></i></span>

                                                        <span class="dash__w-text">0</span>

                                                        <span class="dash__w-name">Cancel Orders</span></div>
                                                </li>
                                                <li>
                                                    <div class="dash__w-wrap">

                                                        <span class="dash__w-icon dash__w-icon-style-3"><i class="far fa-heart"></i></span>

                                                        <span class="dash__w-text">0</span>

                                                        <span class="dash__w-name">Wishlist</span></div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <!--====== End - Dashboard Features ======-->
                                </div>
                                <div class="col-lg-9 col-md-12">
                                    <div class="dash__box dash__box--shadow dash__box--radius dash__box--bg-white">
                                        <div class="dash__pad-2">
                                            <h1 class="dash__h1 u-s-m-b-14">My Returns & Cancellations</h1>

                                            <span class="dash__text">There are no returns & cancellations yet.</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--====== End - Section Content ======-->
            </div>
            <!--====== End - Section 2 ======-->
        </div>
        <!--====== End - App Content ======-->


        {% endblock content %}

products/templates/head.html
{% load static %}


    <meta charset="UTF-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="images/favicon.png" rel="shortcut icon">
    <title>Costumebase - Electronics, Apparel, Computers, Books, DVDs & more</title>

    <!--====== Google Font ======-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800" rel="stylesheet">

    
<!-- 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/alerts-css@1.0.2/assets/css/alerts-css.min.css"> -->

    <link rel="stylesheet" href="{% static 'css/alerts-css.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/alerts-css.min.css' %}"> -->

    
    

    <!--====== Vendor Css ======-->
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">

    <!--====== Utility-Spacing ======-->
    <link rel="stylesheet" href="{% static 'css/utility.css' %}">

    <!--====== App ======-->
    <link rel="stylesheet" href="{% static 'css/app.css' %}">

    <link rel="stylesheet" href="{% static 'css/topcat.css' %}">

    <link rel="stylesheet" href="{% static 'css/nonabr.css' %}">
    
    <link rel="stylesheet" media="screen" href="{% static 'css/navbar.css' %}">

    <link rel="stylesheet" href="{% static 'css/jquary.css' %}">


    <script src="https://code.jquery.com/jquery-3.6.0.min.js" 
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>