blog/urls.py
from django.urls import path 

from .import views

app_name = 'blog'

urlpatterns = [
    

    path('', views.BlogView.as_view(), name='blogview'),

    path('<slug>/', views.BlogDetail.as_view(), name='blogdetail'),

    path('search/', views.SearchView.as_view(), name='search'),


] 

cart/urls.py
from django.urls import path 

from .import views

app_name = 'cart'

urlpatterns = [
    

    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),

    path('shopcart/', views.shopcart, name='shopcart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),

    path('add-cart/<int:id>/', views.add_one_product, name='addcart'),
    path('remove-cart/<int:id>/', views.remove_one_product, name='romovecart'),

    path('remove_variant_product/<int:id>/', views.remove_variant_product, name='remove_variant_product'),
    path('add_variant_product/<int:id>/', views.add_variant_product, name='add_variant_product'),


    # path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),


] 

costumebase/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    
    path('', include('products.urls', namespace='product')),

    path('cart/', include('cart.urls', namespace='cart')),
    
    path('order/', include('order.urls', namespace='order')),
    
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

    path('blog/', include('blog.urls', namespace='blog')),




    path('register/', include('accounts.urls', namespace='register')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),


]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path 

from .import views

app_name = 'product'

urlpatterns = [


   
    path('', views.LandingPage.as_view(), name='index'),

    path('products/', views.Product_Index.as_view(), name='product-index'),
    # path('product-detail/<slug>/',views.Product_Detail.as_view(), name='product-detail'),
    path('add_to_wish/<int:id>/', views.add_to_wish, name ='add_to_wish'),

    path('product-detail/<int:id>/<slug:slug>/', views.product_detail, name='product-detail'),

    


    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),

    path('addcomment/<int:id>/', views.addcomment, name='addcomment'),


    path('category/<slug>/', views.Category_Detail.as_view(), name='category-detail'),


   
    # Search
    path('search/', views.SearchView.as_view(), name='search'),
    path('auto/', views.auto, name='auto'),


    # Wishlist

    path('wish/', views.Wish_View.as_view(), name='wish'),
    path('delete_wish_item/<int:id>/', views.delete_wish_item, name='delete_wish_item'),



    # Shop
    path('shops/', views.Shops.as_view(), name='shops'),
    path('free-shipping/', views.Free_Shipping.as_view(), name='free-shipping'),

    # Filter
    path('filterMdata/',views.filter_data, name='filter_data'),
    path('product-list/', views.Product_List.as_view(), name='product-list'),


    # Message

    path('send-message/<int:id>/<str:name>/',views.send_massage, name='send-message'),

    # path('product-detail-message/<int:id>/', views.massage, name='product-detail-message'),

    # path('detail/', views.)

    path("messages/", views.index, name="index"),

    path("message_search/", views.search, name="message_search"),

    path("addfriend/<str:name>", views.addFriend, name="addFriend"),
    
    path("chat/<str:username>", views.chat, name="chat"),
    
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),
   

]

cart/models.py
from products.models import Product, Variants
from django.db import models
from django.forms import ModelForm

from accounts.models import *


class Wishlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    # variant = models.ForeignKey(Variants, on_delete=models.SET_NULL, blank=True, null=True) # relation with varinat
    def __str__(self):
        return str(self.product)
    

class ShopCart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL, blank=True, null=True) # relation with varinat
    quantity = models.IntegerField()


    def __str__(self):
        return self.product.name

    @property
    def price(self):
        return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.product.price)

    @property
    def varamount(self):
        return (self.quantity * self.variant.price)

  
           


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']



# class OrderForm(ModelForm):
#     class Meta:
#         model = Order
#         fields = ['first_name','last_name','address','phone','city','country']



# class Order(models.Model):
#     STATUS = (
#         ('New', 'New'),
#         ('Accepted', 'Accepted'),
#         ('Preaparing', 'Preaparing'),
#         ('OnShipping', 'OnShipping'),
#         ('Completed', 'Completed'),
#         ('Canceled', 'Canceled'),
#     )
#     user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
#     code = models.CharField(max_length=5, editable=False )
#     first_name = models.CharField(max_length=10)
#     last_name = models.CharField(max_length=10)
#     phone = models.CharField(blank=True, max_length=20)
#     address = models.CharField(blank=True, max_length=150)
#     city = models.CharField(blank=True, max_length=20)
#     country = models.CharField(blank=True, max_length=20)
#     total = models.FloatField()
#     status=models.CharField(max_length=10,choices=STATUS,default='New')
#     ip = models.CharField(blank=True, max_length=20)
#     adminnote = models.CharField(blank=True, max_length=100)
#     create_at=models.DateTimeField(auto_now_add=True)
#     update_at=models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return self.user.first_name

# class OrderProduct(models.Model):
#     STATUS = (
#         ('New', 'New'),
#         ('Accepted', 'Accepted'),
#         ('Canceled', 'Canceled'),
#     )
#     order = models.ForeignKey(Order, on_delete=models.CASCADE)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     variant = models.ForeignKey(Variants, on_delete=models.SET_NULL,blank=True, null=True) # relation with varinat
#     quantity = models.IntegerField()
#     price = models.FloatField()
#     amount = models.FloatField()
#     status = models.CharField(max_length=10, choices=STATUS, default='New')
#     create_at = models.DateTimeField(auto_now_add=True)
#     update_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return self.product.title

cart/forms.py
from django import forms


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))

cart/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views import generic
from products.models import *
from .models import *
from order.models import *

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist

from .forms import CouponForm





@login_required(login_url='/register/customer_login/')

def addtoshopcart(request, id):
    url = request.META.get('HTTP_REFERER')
   
    current_user = request.user  # Access User Session information
    product= Product.objects.get(pk=id)
    print(product, "hollly fujck")

    variantid = request.POST.get('variantid', None)

    print(variantid, 'checking variaents id man')

    if product.variant != 'None':
         # from variant add to cart

         # it will show if it has in cart
    
        checkinvariant = ShopCart.objects.filter(variant_id=variantid, user_id=current_user.id)
        
        print(checkinvariant, "variantid vs variant_id")

        if checkinvariant:
            control = 1 # The product is in the cart
            print("i am variation but still not in cart ")

        else:
            control = 0 # The product is not in the cart"""
            print("i am variation but in cart ")

        print("i do have variations")
    else:
        checkinproduct = ShopCart.objects.filter(product_id=id, user_id=current_user.id) # Check product in shopcart

        print(checkinproduct, "product_id vs id")

        if checkinproduct:
            control = 1 # The product is in the cart
            print('i in cart as product')
        else:
            control = 0 # The product is not in the cart"""
            print('im not in cart as product')
        print("i dont have any variations")
        

    if request.method == 'POST':  # if there is a post
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control==1: # Update  shopcart
                if product.variant == 'None':
                    data = ShopCart.objects.get(product_id=id, user_id=current_user.id)
                    print(data, "checking none variatents formvalidate ")
                else:
                    data = ShopCart.objects.get(product_id=id, variant_id=variantid, user_id=current_user.id)
                    print(data, "checking variatents formvalidate ")
                data.quantity += form.cleaned_data['quantity']
                data.save()  # save data
            else : # Inser to Shopcart
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.variant_id = variantid
                data.quantity = form.cleaned_data['quantity']
                data.save()
                print("saved data let's go")
        messages.success(request, "Product added to Shopcart ")
        return redirect('cart:shopcart')
    else: # if there is no post
        if control == 1:  # Update  shopcart
            data = ShopCart.objects.get(product_id=id, user_id=current_user.id)
            data.quantity += 1
            data.save()  #
        else:  #  Inser to Shopcart
            data = ShopCart()  # model ile bağlantı kur
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.variant_id = None
            data.save()  #
        messages.success(request, "Product added to Shopcart")
        return redirect('cart:shopcart')

# class OrderSummaryView(LoginRequiredMixin, View):
#     def get(self, *args, **kwargs):
#         try:
#             order = Order.objects.filter(user=self.request.user, ordered=False)
#             context = {
#                 'order': order,
#                 'couponform': CouponForm(),
#                 'DISPLAY_COUPON_FORM': True
#             }
#             return render(self.request, 'eco/basket.html', context)
#         except ObjectDoesNotExist:
#             messages.warning(self.request, "You do not have an active order")
#             return redirect("eco:EcoIndex")

# def get_total(self):
#     total = 0
#     amount = models.FloatField()
#     for order_item in self.items.all():
#         total += order_item.get_final_price()
#     if self.coupon:
#         total -= self.coupon.amount
#     return total


@login_required(login_url='/register/customer_login/')

def shopcart(request):
    current_user = request.user
    category = Category.objects.all()  # Access User Session information
    shopcart = ShopCart.objects.filter(user=request.user)

    total = 0
    for i in shopcart:

        if i.product.variant == "None":

            total += i.product.price * i.quantity
        else:
            if i.variant != None:
                total += i.variant.price * i.quantity
  



    #     print(total, "that's mean i am not ")

        
    context={'shopcart': shopcart,
             'category': category,
             'total':total,

             }
    return render(request,'cart.html',context)





@login_required(login_url='/register/customer_login/')

def deletefromcart(request,id):
    current_user = request.user
    ShopCart.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, "Your item deleted form Cart.")
    return redirect('cart:shopcart')


@login_required(login_url='/register/customer_login/')

def remove_one_product(request, id):
    current_user = request.user
    product = Product.objects.get(pk=id)
    print(product, 'say your product ')                                  
    shopcart = ShopCart.objects.filter(product_id=id, user_id=current_user.id)
    print(shopcart, "say your")
    if shopcart.exists():
        for shop in shopcart:
            if shop.quantity > 1:
                shop.quantity -= 1
                shop.save()
                print("i am ot less than 1")
            else:
                shop.delete()
                print("i am more than 1 ")
    else:
        print("Your cart has minumum product")

    return redirect('cart:shopcart')

@login_required(login_url='/register/customer_login/')

def add_one_product(request, id):
    current_user = request.user
    product = Product.objects.get(pk=id)
    print(product, 'say your product ')                                  
    shopcart = ShopCart.objects.filter(product_id=id, user_id=current_user.id)
    print(shopcart, "say your")
    if shopcart.exists():
        for shop in shopcart:
            if shop.quantity > 0:
                shop.quantity += 1
                shop.save()
                print("i am ot less than 1")
            else:
                shop.add(product)
                print("i am more than 1 ")
    else:
        print("Your cart has minumum product")

    return redirect('cart:shopcart')



@login_required(login_url='/register/customer_login/')

def remove_variant_product(request, id):
    current_user = request.user
    product = Variants.objects.get(pk=id)
    print(product, 'say your product ')

    shopcart = ShopCart.objects.filter(variant_id=product.id, user_id=current_user.id)
    print(shopcart.values(), 'trying to price some values')

    if shopcart.exists():
        for shop in shopcart:
            if shop.quantity > 1:
                shop.quantity -= 1
                shop.save()
                print("i am ot less than 1")
            else:
                shop.delete()
                print("i am more than 1 ")
    else:
        print("Your cart has minumum product")

    return redirect('cart:shopcart')


@login_required(login_url='/register/customer_login/')

def add_variant_product(request, id):

    current_user = request.user
    product = Variants.objects.get(pk=id)
    print(product, 'say your product ')

    shopcart = ShopCart.objects.filter(variant_id=product.id, user_id=current_user.id)
    print(shopcart.values(), 'trying to price some values')

    if shopcart.exists():
        for shop in shopcart:
            if shop.quantity > 0:
                shop.quantity += 1
                shop.save()
                print("i am ot less than 1")
            else:
                shop.delete()
                print("i am more than 1 ")
    else:
        print("Your cart has minumum product")

    return redirect('cart:shopcart')

cart/templates/addtocart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <h3>Product added to cart successfully.</h3>
        
    </div>
</body>
</html>

cart/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800&display=swap");

body {
    background-color: #eee;
    font-family: "Poppins", sans-serif
}

.container {
    height: 100vh
}

.card {
    background-color: #fff;
    position: relative;
    width: 350px;
    border: none
}

.percent {
    width: 63px;
    height: 30px;
    position: absolute;
    background: red;
    color: #fff;
    border-radius: 3px;
    display: flex;
    justify-content: center;
    align-items: center;
    right: 0;
    border-bottom-left-radius: 15px;
    padding: 10px
}

.card-image {
    padding: 30px;
    display: flex;
    align-items: center;
    justify-content: center
}

.card-inner {
    padding: 20px
}

.price span {
    color: orange;
    font-weight: 600;
    font-size: 20px
}

.price sup {
    color: orange;
    font-weight: 600;
    font-size: 14px;
    top: -3px
}

.details {
    border-radius: 20px;
    width: 110px;
    height: 40px;
    display: flex;
    justify-content: center;
    align-items: center
}

.wishlist {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    color: #f7a754;
    background: #fdeddc;
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    transition: 0.5s all;
    font-size: 15px
}

.wishlist:hover {
    color: #fff;
    background: #f7a754
}

.cart {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    color: #fff;
    background: green;
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    transition: 0.5s all;
    margin-left: 5px;
    font-size: 15px
}
    </style>
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center">
        <div class="card"> <span class="percent">-10%</span>
            <div class="card-image"> <img src="{{object.image_main.url}}" width="250"> </div>
            <div class="card-inner"> <span></span>
                
                
                {% if product.variant != 'None'   %}

                {{variant.name}}
                        
                <h3 class="mb-0 font-weight-semibold">${{variant.price}} v</h3>

                {% else %}
                <h3 class="mb-0 font-weight-semibold">${{product.price}}</h3>
                                        
                {% endif %}
                <div class="price">

                     <span>$22.99</span> <sup>$20.99</sup> </div>
                <div class="mt-3 d-flex justify-content-between align-items-center">
                    
                    
                    <div class="d-flex flex-row"> <span class="wishlist">
                        
                        <i class="fa fa-heart"></i></span> 
                        
                        <span class="cart"><a href="{% url 'cart:addtoshopcart' product.id %}"><i class="fa fa-shopping-cart"></i></a></span> 
                    
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

cart/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {
    margin: 0;
    font-family: Roboto, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    font-size: .8125rem;
    font-weight: 400;
    line-height: 1.5385;
    color: #333;
    text-align: left;
    background-color: #2196F3
}

.mt-50 {
    margin-top: 50px
}

.mb-50 {
    margin-bottom: 50px
}

.card {
    position: relative;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-direction: column;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 1px solid rgba(0, 0, 0, .125);
    border-radius: .1875rem
}

.card-img-actions {
    position: relative
}

.card-body {
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    padding: 1.25rem;
    text-align: center
}

.card-img {
    width: 350px
}

.star {
    color: red
}

.bg-cart {
    background-color: orange;
    color: #fff
}

.bg-cart:hover {
    color: #fff
}

.bg-buy {
    background-color: green;
    color: #fff;
    padding-right: 29px
}

.bg-buy:hover {
    color: #fff
}

a {
    text-decoration: none !important
}
    </style>
</head>
<body>
    <div class="container d-flex justify-content-center mt-50 mb-50">
        <div class="row">
                  {% for product in object_list  %}
                    
               
            <div class="col-md-4 mt-2">
                <div class="card">
                    <div class="card-body">
                        <div class="card-img-actions"> 
                            
                            <img src="{{product.image_main.url}}" class="card-img img-fluid" width="96" height="350" alt=""> </div>
                    </div>
                    <div class="card-body bg-light text-center">
                        <div class="mb-2">
                            <h6 class="font-weight-semibold mb-2">
                                
                                
                                
                                <a href="{% url 'cart:product-detail' product.id product.slug %}" class="text-default mb-2"
                                 data-abc="true">{{product.name}}</a> 

                                </h6> <a href="#" class="text-muted" data-abc="true">{{product.name.name}}</a>
                        </div>

  
                  
                        <h3 class="mb-0 font-weight-semibold">${{product.price}}</h3>
                                                
                    
                       
                        
                        <a href="{% url 'cart:addtocart' product.id %}" class="btn bg-cart">
                            
                            <i class="fa fa-cart-plus mr-2"></i> Add to cart</a>
                    </div>
                </div>
            </div>

         {% endfor %}
       
            
        </div>
    </div>
    
</body>
</html>

cart/templates/wishlist.html
{% extends "base.html" %}

{% load static %}

{% block content %}
  




        <!--====== App Content ======-->
        <div class="app-content">

            <!--====== Section 1 ======-->
            <div class="u-s-p-y-60">

                <!--====== Section Content ======-->
                <div class="section__content">
                    <div class="container">
                        <div class="breadcrumb">
                            <div class="breadcrumb__wrap">
                                <ul class="breadcrumb__list">
                                    <li class="has-separator">

                                        <a href="index.html">Home</a></li>
                                    <li class="is-marked">

                                        <a href="wishlist.html">Wishlist</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--====== End - Section 1 ======-->


            <!--====== Section 2 ======-->
            <div class="u-s-p-b-60">

                <!--====== Section Intro ======-->
                <div class="section__intro u-s-m-b-60">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="section__text-wrap">
                                    <h1 class="section__heading u-c-secondary">Wishlist</h1>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--====== End - Section Intro ======-->


                <!--====== Section Content ======-->
                <div class="section__content">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                {% for wish in wish %}
                                  
                             
                                <!--====== Wishlist Product ======-->
                                <div class="w-r u-s-m-b-30">
                                    <div class="w-r__container">
                                        <div class="w-r__wrap-1">
                                            <div class="w-r__img-wrap">

                                                <img class="u-img-fluid" src="{{wish.product.image_main.url}}" alt=""></div>
                                            <div class="w-r__info">

                                                <span class="w-r__name">

                                                    <a href="{{wish.product.get_absolute_url}}">{{wish.product.name}}</a></span>

                                                <span class="w-r__category">

                                                    <a href="shop-side-version-2.html">Electronics</a></span>

                                                <span class="w-r__price">$125.00

                                                    <span class="w-r__discount">$160.00</span></span></div>
                                        </div>
                                        <div class="w-r__wrap-2">

                                            <!-- <a class="w-r__link btn--e-brand-b-2" data-modal="modal" data-modal-id="#add-to-cart">ADD TO CART</a> -->

                                            <a class="w-r__link btn--e-transparent-platinum-b-2" href="{{wish.product.get_absolute_url}}">VIEW</a>

                                            <a class="w-r__link btn--e-transparent-platinum-b-2" href="#">REMOVE</a></div>
                                    </div>
                                </div>
                                <!--====== End - Wishlist Product ======-->

                       {% endfor %}
                                
                            </div>
                            <div class="col-lg-12">
                                <div class="route-box">
                                    <div class="route-box__g">

                                        <a class="route-box__link" href="shop-side-version-2.html"><i class="fas fa-long-arrow-alt-left"></i>

                                            <span>CONTINUE SHOPPING</span></a></div>
                                    <div class="route-box__g">

                                        <a class="route-box__link" href="wishlist.html"><i class="fas fa-trash"></i>

                                            <span>CLEAR WISHLIST</span></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--====== End - Section Content ======-->
            </div>
            <!--====== End - Section 2 ======-->
        </div>
        <!--====== End - App Content ======-->


        <!--====== Main Footer ======-->
      

        <!--====== Modal Section ======-->


        <!--====== Add to Cart Modal ======-->
        <div class="modal fade" id="add-to-cart">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content modal-radius modal-shadow">

                    <button class="btn dismiss-button fas fa-times" type="button" data-dismiss="modal"></button>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-lg-6 col-md-12">
                                <div class="success u-s-m-b-30">
                                    <div class="success__text-wrap"><i class="fas fa-check"></i>

                                        <span>Item is added successfully!</span></div>
                                    <div class="success__img-wrap">

                                        <img class="u-img-fluid" src="{% static 'images/product/electronic/product1.jpg' %}" alt=""></div>
                                    <div class="success__info-wrap">

                                        <span class="success__name">Beats Bomb Wireless Headphone</span>

                                        <span class="success__quantity">Quantity: 1</span>

                                        <span class="success__price">$170.00</span></div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12">
                                <div class="s-option">

                                    <span class="s-option__text">1 item (s) in your cart</span>
                                    <div class="s-option__link-box">

                                        <a class="s-option__link btn--e-white-brand-shadow" data-dismiss="modal">CONTINUE SHOPPING</a>

                                        <a class="s-option__link btn--e-white-brand-shadow" href="cart.html">VIEW CART</a>

                                        <a class="s-option__link btn--e-brand-shadow" href="checkout.html">PROCEED TO CHECKOUT</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!--====== End - Add to Cart Modal ======-->
        <!--====== End - Modal Section ======-->

    <!--====== End - Main App ======-->


    <!--====== Google Analytics: change UA-XXXXX-Y to be your site's ID ======-->


    {% endblock content %}