blog/urls.py
from django.urls import path 

from .import views

app_name = 'blog'

urlpatterns = [
    

    path('', views.BlogView.as_view(), name='blogview'),

    path('<slug>/', views.BlogDetail.as_view(), name='blogdetail'),

    path('search/', views.SearchView.as_view(), name='search'),


] 

costumebase/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    
    path('', include('products.urls', namespace='product')),

    path('cart/', include('cart.urls', namespace='cart')),
    
    path('order/', include('order.urls', namespace='order')),
    
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

    path('blog/', include('blog.urls', namespace='blog')),




    path('register/', include('accounts.urls', namespace='register')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),


]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path 

from .import views

app_name = 'dashboard'

urlpatterns = [
    
 # ----------------------------------------- Vendor -------------------------------------

    path('index/', views.dashboard, name='index'),

    path('chart/', views.Chart.as_view(), name='chart'),

    path('add-product/', views.Add_Product.as_view(), name='add-product'),

    path('product-list/', views.Product_List.as_view(), name='product-list'),

    path('add-image/', views.add_image, name='add-image'),
    path('add-variant/', views.add_product_variation, name='add-varaint'),
    path('image-list/', views.Image_list.as_view(), name='image-list'),

    path('new-order/', views.New_Order_list.as_view(), name='new-order'),



    path('delivered-product-list/', views.Delivered_Product_list.as_view(), name='delivered-product-list'),
    path('detail-delivered-product/<int:pk>/', views.Detail_Delivered_Product.as_view(), name='detail-delivered-product'),

    #.......................................... Chart ........................................

    path('pie/', views.pie_chart, name = 'pie'),
    path('population-chart/', views.population_chart, name='population-chart'),
    path('chart/sales/<int:year>/', views.get_sales_chart, name='chart-sales'),

    




    # -------------------------------------- Customer -----------------------------------

    path('user-profile/', views.Customer_Profile.as_view(), name='user-profile'),
    path('user-dashboard/',views.User_Dashboard.as_view(), name='user-dashboard'),
    path('user-order/', views.User_Order.as_view(), name='user-order'),


    # ........................................ Message .................................

    path("chat/<str:username>", views.vendor_chat, name="vendor_chat"),


    path('user-message/', views.User_Message.as_view(), name='user-message'),

    path('message-detail/<int:pk>/', views.Message_Detail.as_view(), name='message_detail'),


    
]

blog/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.db.models import Q
# from tinymce import HTMLField
from django.template.defaultfilters import slugify



class PostView(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural='4. PostView'

    def __str__(self):
        return self.user.email

class Author(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100)
    thumbnail = models.ImageField()
    detail = models.TextField(max_length=100)

    class Meta:
        verbose_name_plural='1. Author'

    def __str__(self):
        return self.user.email


class Blog_Category(models.Model):
    title = models.CharField(max_length=20)
    detail = models.TextField(blank=True)
    featured = models.BooleanField(default=True)
 
    # post = models.ForeignKey('Post', on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name_plural = "2. Categories"
    
    def __str__(self):
        return self.title
    # def get_absolute_url(self):
    #     return reverse('post-category', args=[self.title])
    def get_absolute_url(self):
        return reverse('post-category', kwargs={
            'slug': self.slug
        })

class Post(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    featured = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    #content = HTMLField()
    user = models.ForeignKey(Author,on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    category = models.ForeignKey(Blog_Category, related_name='categories', on_delete=models.CASCADE)
    tags = TaggableManager()
    slug = models.SlugField(null=False, unique=True)


    class Meta:
        verbose_name_plural='3. Post'


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={
            'slug': self.slug
        })

    def get_update_url(self):
        return reverse('post-update', kwargs={
            'slug': self.slug
        })

    def get_delete_url(self):
        return reverse('post-delete', kwargs={
            'slug': self.slug
        })

cart/models.py
from products.models import Product, Variants
from django.db import models
from django.forms import ModelForm

from accounts.models import *


class Wishlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    # variant = models.ForeignKey(Variants, on_delete=models.SET_NULL, blank=True, null=True) # relation with varinat
    def __str__(self):
        return str(self.product)
    

class ShopCart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL, blank=True, null=True) # relation with varinat
    quantity = models.IntegerField()


    def __str__(self):
        return self.product.name

    @property
    def price(self):
        return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.product.price)

    @property
    def varamount(self):
        return (self.quantity * self.variant.price)

  
           


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']



# class OrderForm(ModelForm):
#     class Meta:
#         model = Order
#         fields = ['first_name','last_name','address','phone','city','country']



# class Order(models.Model):
#     STATUS = (
#         ('New', 'New'),
#         ('Accepted', 'Accepted'),
#         ('Preaparing', 'Preaparing'),
#         ('OnShipping', 'OnShipping'),
#         ('Completed', 'Completed'),
#         ('Canceled', 'Canceled'),
#     )
#     user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
#     code = models.CharField(max_length=5, editable=False )
#     first_name = models.CharField(max_length=10)
#     last_name = models.CharField(max_length=10)
#     phone = models.CharField(blank=True, max_length=20)
#     address = models.CharField(blank=True, max_length=150)
#     city = models.CharField(blank=True, max_length=20)
#     country = models.CharField(blank=True, max_length=20)
#     total = models.FloatField()
#     status=models.CharField(max_length=10,choices=STATUS,default='New')
#     ip = models.CharField(blank=True, max_length=20)
#     adminnote = models.CharField(blank=True, max_length=100)
#     create_at=models.DateTimeField(auto_now_add=True)
#     update_at=models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return self.user.first_name

# class OrderProduct(models.Model):
#     STATUS = (
#         ('New', 'New'),
#         ('Accepted', 'Accepted'),
#         ('Canceled', 'Canceled'),
#     )
#     order = models.ForeignKey(Order, on_delete=models.CASCADE)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     variant = models.ForeignKey(Variants, on_delete=models.SET_NULL,blank=True, null=True) # relation with varinat
#     quantity = models.IntegerField()
#     price = models.FloatField()
#     amount = models.FloatField()
#     status = models.CharField(max_length=10, choices=STATUS, default='New')
#     create_at = models.DateTimeField(auto_now_add=True)
#     update_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return self.product.title

products/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.html import mark_safe
from django.shortcuts import reverse
from django.forms import ModelForm
import uuid
from django.db.models import Avg, Count


from .utilis import create_new_ref_number

from accounts.models import Vendor, Buyer





class Category(MPTTModel):
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children', db_index=True)
    image = models.ImageField(upload_to="category/images", null=True, blank=True)
    top_category = models.BooleanField(default=False)
    slug = models.SlugField(null=False, unique=True)

    class Meta:
        verbose_name_plural='2. Categories'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("product:category-detail", kwargs={
            'slug': self.slug
        })

    class MPTTMeta:
        order_insertion_by = ['name']


class Shop(models.Model):
    name=models.CharField(max_length=100, unique=True)
    vendor = models.ForeignKey(Vendor, related_name='shop_owner', on_delete=models.CASCADE,
                                null=True, blank=True)  # need to be changed
    image=models.ImageField(upload_to="shop/images")
    discription = models.CharField(max_length=250)

    class Meta:
        verbose_name_plural='3. Shops'

    def __str__(self):
        return self.name
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

class Brand(models.Model):
    name=models.CharField(max_length=100, unique=True)
    image=models.ImageField(upload_to="brand/images")

    class Meta:
        verbose_name_plural='4. Brands'

    def __str__(self):
        return self.name


class Product(models.Model):
    
    VARIANTS = (
            ('None', 'None'),
            ('Size', 'Size'),
            ('Color', 'Color'),
            ('Size-Color', 'Size-Color'),

        )

    vendor = models.ForeignKey(Vendor, related_name='vendors', on_delete=models.CASCADE, null=True, blank=True)
    shop = models.ForeignKey(Shop, related_name='shops', on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, related_name='brands', on_delete=models.CASCADE, null=True, blank=True)
    category = TreeForeignKey(Category, related_name='categories', on_delete=models.CASCADE)
     
    name = models.CharField(max_length=15, unique=True)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)

    image_main = models.ImageField(upload_to='product/images')
    variant=models.CharField(max_length=10,choices=VARIANTS, default='Color')
    amount=models.IntegerField(default=0)

    description = models.TextField(verbose_name='Product short description', max_length=250, blank=False)

    is_for_sale = models.BooleanField(default=True)
    is_free_shipping = models.BooleanField(default=False)


    featured = models.BooleanField(default=False, blank=True)
    special = models.BooleanField(default=False, blank=True)
    weekly = models.BooleanField(default=False, blank=True)
    flash_product = models.BooleanField(default=False, blank=True)

    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    slug = models.SlugField(unique=True, blank=True)

    class Meta:
        verbose_name_plural='1. Products'

        

    def __str__(self):
        return self.name

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image_main.url))

    def get_absolute_url(self):
        return reverse("product:product-detail", kwargs={
           'id':self.pk, 'slug': self.slug
        })

    @property
    def count_sold(self):
        return self.orderproduct_set.filter().count()

    def avaregereview(self):
        reviews = Comment.objects.filter(product=self, status='True').aggregate(avarage=Avg('rate'))
        avg=0
        if reviews["avarage"] is not None:
            avg=float(reviews["avarage"])
        return avg

    def countreview(self):
        reviews = Comment.objects.filter(product=self, status='True').aggregate(count=Count('id'))
        cnt=0
        if reviews["count"] is not None:
            cnt = int(reviews["count"])
        return cnt

   

    


class Images(models.Model):
    vendor = models.ForeignKey(Vendor, related_name='vendor_image', on_delete=models.CASCADE, null=True, blank=True)
    product=models.ForeignKey(Product,on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    image = models.ImageField(blank=True, upload_to='product/images')

    def __str__(self):
        return self.name
    
    def image_tag(self):

        if self.image:
            return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
        else:

           return "/static/images/gf.png"

    class Meta:
        verbose_name_plural='5. Images'


class Color(models.Model):
    name = models.CharField(max_length=20, unique=True)
    code = models.CharField(max_length=10, unique=True)  

    def __str__(self):
        return self.name

    def color_tag(self):
        return mark_safe('<div style="width:30px; height:30px; background-color:%s"></div>' % (self.code))

    class Meta:
        verbose_name_plural='6. Colors'


class Size(models.Model):
    name = models.CharField(max_length=20, unique=True)
    code = models.CharField(max_length=10, unique=True)  

    def __str__(self):
        return self.code
    
    class Meta:
        verbose_name_plural='7. Sizes'


class Variants(models.Model):
    
    vendor = models.ForeignKey(Vendor, related_name='vendor_variation', on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, blank=True,null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE,blank=True,null=True)
    size = models.ForeignKey(Size, on_delete=models.CASCADE,blank=True,null=True)
    image_id = models.IntegerField(blank=True,null=True,default=0)    
    quantity = models.IntegerField(default=1)
    price = models.FloatField()

    def __str__(self):
        return self.product.name

    def image(self):
        img = Images.objects.get(id=self.image_id)
        if img.id is not None:
             varimage=img.image.url
        else:
            varimage=""
        return varimage

    def image_tag(self):
        img = Images.objects.get(id=self.image_id)
        if img.id is not None:
             return mark_safe('<img src="{}" height="50"/>'.format(img.image.url))
        else:
            return ""

    class Meta:
        verbose_name_plural='8. Variants'



class Comment(models.Model):

    STATUS = (
        ('New', 'New'),
        ('True', 'True'),
        ('False', 'False'),
    )
    product = models.ForeignKey(Product,on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey(Buyer, on_delete=models.CASCADE,  blank=True, null=True)
    name = models.CharField(max_length=50, blank=True)
    subject = models.CharField(max_length=50, blank=True)
    comment = models.TextField(blank=True, max_length=300)
    rate = models.FloatField(default=1, blank=True)
    ip = models.CharField(max_length=20, blank=True)
    status=models.CharField(max_length=10,choices=STATUS, default='True')
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name_plural='9. Comments'

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'subject', 'comment', 'rate']

dashboard/forms.py
from django import forms
from django.forms import fields
from products.models import *


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['vendor']
        fields = ['brand', 'shop', 'category', 'variant', 'amount', 'name', 'price', 
        'discount_price', 'image_main', 'is_for_sale', 'is_free_shipping', 'description']


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Images
        exclude = ['vendor']
        fields = ['product', 'name', 'image']

   

class ProductVariation(forms.ModelForm):
    class Meta:
        model = Variants
        exclude = ['vendor']
        fields = ['name', 'product', 'color', 'size', 'image_id', 'quantity', 'price']

        

dashboard/templates/add_image.html
{% extends "dash_base.html" %}

{% load static %}

{% block content %}


  

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    


 <label for="id_product">Product:</label>
 
 <select name="product" required="" id="id_product">

<!--   
    <option value="" selected="">---------</option> -->
  
{% for p in productb  %}
  
    <option value="{{ p.id }}">{{p.name}}</option>

 {% endfor %}
  
  </select>
  
  <label for="id_name">Name:</label>
  
  <input type="text" name="name" maxlength="50" id="id_name">

  <label for="id_image">Image:</label>
  
  <input type="file" name="image" accept="image/*" id="id_image">

   
  
  <button type="submit"> save me </button>
</form>


  
{% endblock content %}

dashboard/templates/dash_footer.html
{% load static %}


           <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>

dashboard/templates/dash_head.html
{% load static %}



<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'dashboard/vendor/fontawesome-free/css/all.min.css' %} " rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'dashboard/css/sb-admin-2.min.css' %} " rel="stylesheet">

</head>

dashboard/templates/dash_topbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <!-- <form
        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form> -->

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 12, 2019</div>
                        <span class="font-weight-bold">A new monthly report is ready to download!</span>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-success">
                            <i class="fas fa-donate text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 7, 2019</div>
                        $290.29 has been deposited into your account!
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-warning">
                            <i class="fas fa-exclamation-triangle text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 2, 2019</div>
                        Spending Alert: We've noticed unusually high spending for your account.
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
            </a>

            <!-- Dropdown - Messages -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                    Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="img/undraw_profile_1.svg"
                            alt="...">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">Hi there! I am wondering if you can help me with a
                            problem I've been having.</div>
                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                    </div>
                </a>
        
                <a class="dropdown-item text-center small text-gray-500" href="{% url 'dashboard:vendor_chat' request.user.username %}">Read More Messages</a>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">

            {% if request.user.is_authenticated and request.user.is_vendor %}
            
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.username}} </span>
                <img class="img-profile rounded-circle"
                    src="img/undraw_profile.svg">
            </a>

            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>

            {% else %}

                     
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                <span class="mr-2 d-none d-lg-inline text-gray-600 small">lol McGee</span>
                <img class="img-profile rounded-circle"
                    src="img/undraw_profile.svg">
            </a>

            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>

            {% endif %}
        </li>

    </ul>

</nav>

dashboard/templates/pie.html
{% extends "dash_base.html" %}

{% load static %}

{% block content %}

<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Charts</h1>
    <p class="mb-4">"{{labels|safe}}"</p>

    <!-- Content Row -->
    <div class="row">

        <div class="col-xl-8 col-lg-7">

            <!-- Area Chart -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Area </h6>
                </div>
                <div class="card-body">

                    <div class="chart-area">

                        <canvas id="myAreaChart"></canvas>

                    </div>

                </div>
            </div>

            <!-- Bar Chart -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
                </div>

                
                <div class="card-body">
                    <div class="chart-bar">
                        <canvas id="population-chart" data-url="{% url 'dashboard:population-chart' %}"></canvas>
                    </div>
           
                </div>
            </div>

        </div>

        <!-- Donut Chart -->
        <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie pt-4">
                        <canvas id="myPieChart"></canvas>
                    </div>
                    <hr>
                    Styling for the donut chart can be found in the
                    <code>/js/demo/chart-pie-demo.js</code> file.
                </div>
            </div>
        </div>

        
    </div>

</div>
  
{% endblock content %}